"""Freeze P203 from P201 sequence, micro-union and P191 priority routes."""
from __future__ import annotations
import csv,json
from pathlib import Path
import numpy as np
import p89_build_dual_consensus_submission as io
H=Path(__file__).resolve().parent;O=H/"runs/p203_current_champion_v1";P89=H/"runs/p89_imu_probability_blend_test_v1/submission_p89_imu_probability_blend.csv";P180=H/"runs/p180_sequence_micro_teacher_v1";P201=H/"runs/p201_p200_soft_sequence_gate_v1";P191=H/"runs/p191_source_truth_calibrated_p150_v1";MIC=H/"runs/p89_verified_micro_union_audit_v1/validation_predictions.npz";P168=H/"runs/p168_historical_micro_union_test_v1/submission_p168_historical_micro_union.csv";P167=H/"runs/p167_combined_teacher_test_v1/submission_p167_combined_teacher.csv";S=("H1_selection","H2_confirmation","H3_independent_fold0")
def cp(p):
 with p.open("r",encoding="utf-8-sig",newline="") as f:return np.asarray([int(r["prediction"]) for r in csv.DictReader(f)])
def main():
 p180=np.load(P180/"oof_predictions.npz");y=p180["labels"];safe=p180["base_prediction"];cur=p180["prediction"];a=np.load(P201/"predictions.npz");seq=np.concatenate([a[f"{n}_held_prediction"] for n in S]);m=np.load(MIC);micro=np.concatenate([m["h1_union"],m["h2_union"],m["h3_union"]]);p202=np.where(seq!=safe,seq,np.where(micro!=safe,micro,safe));b=np.load(P191/"predictions.npz");meta=np.concatenate([b[f"{n}_held_prediction"] for n in S]);out=np.where(meta!=cur,meta,p202);correct=int(np.sum(out==y));assert correct==2193,correct;folds=[int(np.sum(out[x:q]==y[x:q])-np.sum(safe[x:q]==y[x:q])) for x,q in ((0,663),(663,1497),(1497,2470))]
 bt=cp(P89);t180=cp(P180/"submission_p180_sequence_micro.csv");tseq=cp(P201/"submission_soft_sequence.csv");p168=cp(P168);p167=cp(P167);tmicro=np.where(p168!=p167,p168,bt);t202=np.where(tseq!=bt,tseq,np.where(tmicro!=bt,tmicro,bt));tmeta=cp(P191/"submission_p191_calibrated_meta.csv");tout=np.where(tmeta!=t180,tmeta,t202);O.mkdir(parents=True,exist_ok=True);sub=O/"submission_p203_current_champion.csv";io.write_submission(sub,io.read_rows(P89),tout);prob=np.full((405,40),.0005,np.float32);prob[np.arange(405),tout]=.9805;targets=O/"student_test_targets.npz";np.savez_compressed(targets,sample_ids=np.asarray([f"SM_test_{i:04d}" for i in range(1,406)]),target_mask=np.ones(405,bool),emission_probability=prob,structured_distillation_probability=prob,structured_confidence=np.full(405,.9805,np.float32),emission_prediction=tout,structured_distillation_prediction=tout);np.savez_compressed(O/"oof_predictions.npz",sample_ids=p180["sample_ids"],labels=y,base_prediction=safe,p180_prediction=cur,prediction=out)
 report={"stage":"P203_current_deployable_champion","status":"complete","oof":{"rows":len(y),"base_correct":int(np.sum(safe==y)),"correct":correct,"accuracy":correct/len(y),"net_vs_p89":correct-int(np.sum(safe==y)),"fold_nets":folds,"gap_to_0.91":2248-correct},"test":{"changes_vs_p89":int(np.sum(tout!=bt)),"changes_vs_p180":int(np.sum(tout!=t180)),"submission":str(sub.resolve()),"targets":str(targets.resolve()),"test_labels_read":False}};(O/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
