"""Source-user-safe P146 workspace selector on top of P205."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
from p117_transductive_multicandidate_router import load_candidate_splits,loso_scores,select_threshold,fit_score
from p134_frozen_repeat_consensus import probability_lookup
from p143_p142_source_user_safe_selector import build_features
from p216_native_p150_test import test_lookup
from p214_p128_meta_test import read_pred
import p89_build_dual_consensus_submission as io
H=Path(__file__).resolve().parent;O=H/"runs/p224_p205_workspace_selector_v1";P205=H/"runs/p205_fixed_p203_p150_residual_v1/oof_predictions.npz";P205T=H/"runs/p205_fixed_p203_p150_residual_v1/submission_p205_fixed_residual.csv";W=H/"runs/p146_vjepa_workspace_transformer_three_seed_v1/oof_predictions.npz";WT=H/"runs/p221_p146_workspace_test_v1/test_predictions.npz";P89=H/"runs/p89_imu_probability_blend_test_v1/submission_p89_imu_probability_blend.csv";S=("H1_selection","H2_confirmation","H3_independent_fold0")
def al(v,s,t):d={x:i for i,x in enumerate(s.astype(str))};return np.asarray(v)[np.asarray([d[x] for x in t.astype(str)])]
def main():
 tr=load_candidate_splits(full_visual_bank=True,structured_bank=True,legacy_visual_bank=True,hand_object_bank=True,vjepa_dense_bank=True,nonvisual_bank=True,hierarchical_bank=True,epic_bank=True,expanded_bank=True);names=list(next(iter(tr.values())).candidates);lk=probability_lookup(tr);p=np.load(P205);w=np.load(W);mp={v:(int(y),int(x)) for v,y,x in zip(p["sample_ids"].astype(str),p["labels"],p["prediction"])};data={}
 for n in S:
  ids=tr[n].split.sample_ids.astype(str);labels=np.asarray([mp[v][0] for v in ids]);base=np.asarray([mp[v][1] for v in ids]);prob=al(w["probability"],w["sample_ids"],ids);alt=prob.argmax(1);data[n]={"ids":ids,"labels":labels,"base":base,"prob":prob,"alt":alt,"users":tr[n].split.users.astype(str),"x":build_features(ids,base,alt,prob,lk)}
 report={"stage":"P224_P205_workspace_selector","status":"complete","protocol":{"base":"P205","alternative":"P146 workspace","source_LOSO_threshold":True,"held_labels_used_for_selection":False,"test_labels_read":False},"cohorts":{}};outs={}
 for held in S:
  src=[n for n in S if n!=held];ids=np.concatenate([data[n]["ids"] for n in src]);labels=np.concatenate([data[n]["labels"] for n in src]);base=np.concatenate([data[n]["base"] for n in src]);alt=np.concatenate([data[n]["alt"] for n in src]);users=np.concatenate([data[n]["users"] for n in src]);x=np.concatenate([data[n]["x"] for n in src]);gain=(alt==labels).astype(np.int8)-(base==labels).astype(np.int8);score=loso_scores(x,gain,users);sel=select_threshold(score,gain,alt!=base,users);eligible=sel["net"]>0 and sel["minimum_user_gain"]>=0;hs=fit_score(x,gain,data[held]["x"]);q=eligible&(data[held]["alt"]!=data[held]["base"])&(hs>=sel["threshold"]);out=data[held]["base"].copy();out[q]=data[held]["alt"][q];outs[held]=out;bc=int(np.sum(data[held]["base"]==data[held]["labels"]));cor=int(np.sum(out==data[held]["labels"]));report["cohorts"][held]={"source":src,"source_selection":sel,"eligible":bool(eligible),"held":{"base_correct":bc,"correct":cor,"net":cor-bc,"changed":int(q.sum()),"rescue":int(np.sum(q&(data[held]["base"]!=data[held]["labels"])&(out==data[held]["labels"]))),"harm":int(np.sum(q&(data[held]["base"]==data[held]["labels"])&(out!=data[held]["labels"])))}}
  print(json.dumps({"held":held,**report["cohorts"][held]["held"]}),flush=True)
 labels=np.concatenate([data[n]["labels"] for n in S]);base=np.concatenate([data[n]["base"] for n in S]);alt=np.concatenate([data[n]["alt"] for n in S]);out=np.concatenate([outs[n] for n in S]);bc=int(np.sum(base==labels));cor=int(np.sum(out==labels));report["aggregate"]={"rows":len(labels),"base_correct":bc,"alternative_correct":int(np.sum(alt==labels)),"oracle_correct":int(np.sum((base==labels)|(alt==labels))),"correct":cor,"accuracy":cor/len(labels),"net_vs_p205":cor-bc,"fold_nets":[report["cohorts"][n]["held"]["net"] for n in S],"gap_to_0.91":int(np.ceil(.91*len(labels))-cor)}
 ids=np.concatenate([data[n]["ids"] for n in S]);users=np.concatenate([data[n]["users"] for n in S]);x=np.concatenate([data[n]["x"] for n in S]);gain=(alt==labels).astype(np.int8)-(base==labels).astype(np.int8);score=loso_scores(x,gain,users);sel=select_threshold(score,gain,alt!=base,users);eligible=sel["net"]>0 and sel["minimum_user_gain"]>=0;ta=read_pred(P205T);wt=np.load(WT);_,tlk,_=test_lookup(tr,names);rid=wt["sample_ids"].astype(str);tids=np.asarray(list(tlk));safe=np.stack([tlk[v][0] for v in tids]);tp=safe.copy();pos={v:i for i,v in enumerate(tids)};rows=np.asarray([pos[v] for v in rid]);tp[rows]=wt["probability"];wi=names.index("expanded_p146_workspace_token")+1
 for i,v in enumerate(tids):tlk[v][wi]=tp[i]
 talt=tp.argmax(1);tx=build_features(tids,ta,talt,tp,tlk);ts=fit_score(x,gain,tx);q=eligible&(talt!=ta)&(ts>=sel["threshold"]);tout=ta.copy();tout[q]=talt[q];O.mkdir(parents=True,exist_ok=True);sub=O/"submission_p224_workspace_selector.csv";io.write_submission(sub,io.read_rows(P89),tout);report["test"]={"oof_selection":sel,"eligible":bool(eligible),"changes_vs_p205":int(q.sum()),"submission":str(sub.resolve()),"test_labels_read":False};np.savez_compressed(O/"predictions.npz",sample_ids=ids,labels=labels,base_prediction=base,workspace_prediction=alt,prediction=out,test_sample_ids=tids,test_base_prediction=ta,test_workspace_prediction=talt,test_score=ts,test_prediction=tout,**{f"{n}_held_prediction":outs[n] for n in S});(O/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps({"aggregate":report["aggregate"],"test":report["test"]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
