"""P205 consensus pool augmented by native P150 and P146 workspace."""
from __future__ import annotations
import csv,json
from pathlib import Path
import numpy as np
import p89_build_dual_consensus_submission as io
from p193_deployable_candidate_ranker import bank
from p173_vjepa_augmented_group_teacher import build_test_bank
from p206_source_safe_candidate_consensus_pairs import descriptors,select,apply
H=Path(__file__).resolve().parent;O=H/"runs/p225_topk_workspace_p150_consensus_v1";P128=H/"runs/p128_hierarchical_multimodal_full_oof_v1/oof_predictions.npz";P128T=H/"runs/p176_p128_hierarchical_test_v1/test_predictions.npz";P205=H/"runs/p205_fixed_p203_p150_residual_v1/oof_predictions.npz";P205T=H/"runs/p205_fixed_p203_p150_residual_v1/submission_p205_fixed_residual.csv";P150=H/"runs/p150_repeat_branch_confidence_selector_v1/predictions.npz";P216=H/"runs/p216_native_p150_test_v1/predictions.npz";W=H/"runs/p146_vjepa_workspace_transformer_three_seed_v1/oof_predictions.npz";WT=H/"runs/p221_p146_workspace_test_v1/test_predictions.npz";P89=H/"runs/p89_imu_probability_blend_test_v1/submission_p89_imu_probability_blend.csv";S=("H1_selection","H2_confirmation","H3_independent_fold0")
def al(v,s,t):d={x:i for i,x in enumerate(s.astype(str))};return np.asarray(v)[np.asarray([d[x] for x in t.astype(str)])]
def cp(p):
 with p.open("r",encoding="utf-8-sig",newline="") as f:return np.asarray([int(r["prediction"]) for r in csv.DictReader(f)])
def hard(p):q=np.full((len(p),40),.05/39,np.float32);q[np.arange(len(p)),p]=.95;return q
def main():
 tr,names=bank();p=np.load(P205);w=np.load(W);p150=np.load(P150);mp={v:(int(y),int(x)) for v,y,x in zip(p["sample_ids"].astype(str),p["labels"],p["prediction"])};data={}
 for n in S:
  q=tr[n];base=np.asarray([mp[v][1] for v in q["ids"]]);labels=np.asarray([mp[v][0] for v in q["ids"]]);b=np.concatenate((q["bank"],hard(p150[f"{n}_prediction"])[:,None,:],al(w["probability"],w["sample_ids"],q["ids"])[:,None,:]),1);proposal,x=descriptors(b,base);data[n]={**q,"base":base,"labels":labels,"proposal":proposal,"x":x}
 report={"stage":"P225_topk_workspace_P150_consensus","status":"complete","protocol":{"base":"P205","extra_experts":["native_P150","P146_workspace"],"source_pair_rules":True,"held_labels_used_for_selection":False,"test_labels_read":False},"cohorts":{}};outs={}
 for held in S:
  src=[n for n in S if n!=held];rules,audit=select(np.concatenate([data[n]["base"] for n in src]),np.concatenate([data[n]["proposal"] for n in src]),np.concatenate([data[n]["x"] for n in src]),np.concatenate([data[n]["labels"] for n in src]),np.concatenate([data[n]["users"] for n in src]));out,m=apply(data[held]["base"],data[held]["proposal"],data[held]["x"],rules);outs[held]=out;bc=int(np.sum(data[held]["base"]==data[held]["labels"]));cor=int(np.sum(out==data[held]["labels"]));report["cohorts"][held]={"source":src,"eligible_rules":list(rules.values()),"source_audit":audit,"held":{"base_correct":bc,"correct":cor,"net":cor-bc,"changed":int(m.sum()),"rescue":int(np.sum(m&(data[held]["base"]!=data[held]["labels"])&(out==data[held]["labels"]))),"harm":int(np.sum(m&(data[held]["base"]==data[held]["labels"])&(out!=data[held]["labels"])))}}
 labels=np.concatenate([data[n]["labels"] for n in S]);base=np.concatenate([data[n]["base"] for n in S]);out=np.concatenate([outs[n] for n in S]);cor=int(np.sum(out==labels));bc=int(np.sum(base==labels));report["aggregate"]={"rows":len(labels),"base_correct":bc,"correct":cor,"accuracy":cor/len(labels),"net_vs_p205":cor-bc,"fold_nets":[report["cohorts"][n]["held"]["net"] for n in S]}
 rules,audit=select(base,np.concatenate([data[n]["proposal"] for n in S]),np.concatenate([data[n]["x"] for n in S]),labels,np.concatenate([data[n]["users"] for n in S]));test=build_test_bank(names[:21],names[:24]);pt=np.load(P128T);test["bank"]=np.concatenate((test["bank"],al(pt["probabilities"],pt["sample_ids"],test["ids"])[:,None,:]),1);p216=np.load(P216);wt=np.load(WT);safe=test["bank"][:,0,:];wp=safe.copy();pos={v:i for i,v in enumerate(test["ids"])};rows=np.asarray([pos[v] for v in wt["sample_ids"].astype(str)]);wp[rows]=wt["probability"];pb=al(p216["prediction"],p216["sample_ids"],test["ids"]);test["bank"]=np.concatenate((test["bank"],hard(pb)[:,None,:],wp[:,None,:]),1);tb=cp(P205T);proposal,x=descriptors(test["bank"],tb);tout,m=apply(tb,proposal,x,rules);O.mkdir(parents=True,exist_ok=True);sub=O/"submission_p225_consensus.csv";io.write_submission(sub,io.read_rows(P89),tout);report["test"]={"eligible_rules":list(rules.values()),"changes_vs_p205":int(m.sum()),"submission":str(sub.resolve()),"test_labels_read":False};np.savez_compressed(O/"predictions.npz",sample_ids=test["ids"],base_prediction=tb,prediction=tout,**{f"{n}_held_prediction":outs[n] for n in S});(O/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps({"aggregate":report["aggregate"],"cohorts":{n:report["cohorts"][n]["held"] for n in S},"test":report["test"]},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
