"""Freeze the P257-selected global emission=.75 / transition=.4 sequence recipe."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import p89_build_dual_consensus_submission as io
from audit_p87_sequence_decoder import align_metadata,build_sessions,decode_sessions,fit_transition_model
from p117_transductive_multicandidate_router import load_candidate_splits
from p139_soft_sequence_gate import sessions_for,gate_features,select_gate
from p257_adaptive_physical_sequence import dec,emission
H=Path(__file__).resolve().parent;O=H/"runs/p258_fixed_transition04_sequence_v1";SOURCE=H/"runs/p255_repeat_augmented_physical_group_v1/predictions.npz";P89=H/"runs/p89_imu_probability_blend_test_v1/submission_p89_imu_probability_blend.csv";S=("H1_selection","H2_confirmation","H3_independent_fold0");CFG=(.75,.4)
def main():
 data=load_candidate_splits();z=np.load(SOURCE);parts={n:{"ids":data[n].split.sample_ids.astype(str),"labels":data[n].split.labels.astype(int),"base":z[f"{n}_held_prediction"].astype(int),"prob":z[f"{n}_held_probability"].astype(float)} for n in S};report={"stage":"P258_fixed_transition04_physical_sequence","status":"complete","protocol":{"source":"P255","emission_probability_weight":.75,"base_onehot_weight":.25,"transition_weight":.4,"gap_seconds":30.,"trigram_backoff":1.,"beam_width":50,"held_labels_used_for_selection":False,"test_labels_read":False},"cohorts":{}};outs={}
 for held in S:
  src=[n for n in S if n!=held];ids=np.concatenate([parts[n]["ids"] for n in src]);y=np.concatenate([parts[n]["labels"] for n in src]);b=np.concatenate([parts[n]["base"] for n in src]);p=np.concatenate([parts[n]["prob"] for n in src]);sessions=sessions_for(data,ids,src);tr=fit_transition_model(y,sessions,40,1.);seq=decode_sessions(emission(p,b,CFG[0]),sessions,tr,dec(CFG[1]));f=gate_features(p,b,seq);g=select_gate(b,seq,f,y);hs=sessions_for(data,parts[held]["ids"],[held]);hseq=decode_sessions(emission(parts[held]["prob"],parts[held]["base"],CFG[0]),hs,tr,dec(CFG[1]));hf=gate_features(parts[held]["prob"],parts[held]["base"],hseq);q=(hseq!=parts[held]["base"])&(hf[:,g["score_index"]]>=g["threshold"]);out=parts[held]["base"].copy();out[q]=hseq[q];outs[held]=out;bc=int(np.sum(parts[held]["base"]==parts[held]["labels"]));cor=int(np.sum(out==parts[held]["labels"]));report["cohorts"][held]={"source":src,"source_gate":g,"held":{"base_correct":bc,"correct":cor,"net":cor-bc,"changed":int(q.sum())}}
 labels=np.concatenate([parts[n]["labels"] for n in S]);base=np.concatenate([parts[n]["base"] for n in S]);out=np.concatenate([outs[n] for n in S]);cor=int(np.sum(out==labels));bc=int(np.sum(base==labels));report["aggregate"]={"rows":len(labels),"base_correct":bc,"correct":cor,"accuracy":cor/len(labels),"net_vs_p255":cor-bc,"fold_nets":[report["cohorts"][n]["held"]["net"] for n in S],"p256_transition03_correct":2204}
 ids=np.concatenate([parts[n]["ids"] for n in S]);sessions=sessions_for(data,ids,list(S));tr=fit_transition_model(labels,sessions,40,1.);p=np.concatenate([parts[n]["prob"] for n in S]);seq=decode_sessions(emission(p,base,CFG[0]),sessions,tr,dec(CFG[1]));f=gate_features(p,base,seq);g=select_gate(base,seq,f,labels);tids=z["sample_ids"].astype(str);tb=z["prediction"].astype(int);tp=z["probability"].astype(float);meta=align_metadata(H/"data/p85_recording_metadata/test_recording_metadata.csv",tids);ts=build_sessions(np.arange(len(tids)),meta,30.,"anonymous_date");tseq=decode_sessions(emission(tp,tb,CFG[0]),ts,tr,dec(CFG[1]));tf=gate_features(tp,tb,tseq);q=(tseq!=tb)&(tf[:,g["score_index"]]>=g["threshold"]);tout=tb.copy();tout[q]=tseq[q];O.mkdir(parents=True,exist_ok=True);sub=O/"submission_p258_fixed_transition04.csv";io.write_submission(sub,io.read_rows(P89),tout);report["final_gate"]=g;report["test"]={"changes_vs_p255":int(q.sum()),"submission":str(sub.resolve()),"test_labels_read":False};np.savez_compressed(O/"predictions.npz",sample_ids=tids,base_prediction=z["base_prediction"],group_prediction=tb,probability=tp.astype(np.float32),prediction=tout,route=q,**{f"{n}_held_prediction":outs[n] for n in S});(O/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
