"""Add the matched LaViLa frame-token expert to the P177 deployable bank."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import p89_build_dual_consensus_submission as io
from p137_group_classifier_selector import CONFIG,fit_probability,group_features
from p165_deployable_group_teacher import SPLITS,TEST_METADATA,TRAIN_METADATA,concatenate,crossfit,features,lookup_for
from p173_vjepa_augmented_group_teacher import build_train_bank,build_test_bank
H=Path(__file__).resolve().parent;O=H/"runs/p278_centroid_augmented_group_v1";P128=H/"runs/p128_hierarchical_multimodal_full_oof_v1/oof_predictions.npz";P128T=H/"runs/p176_p128_hierarchical_test_v1/test_predictions.npz";L=H/"runs/p158_lavila_frame_token_transformer_single_seed_v1/oof_predictions.npz";LT=H/"runs/p198_lavila_frame_token_test_head_v1/test_predictions.npz";P89=H/"runs/p89_imu_probability_blend_test_v1/submission_p89_imu_probability_blend.csv";CENT=H/"runs/p277_physical_centroid_expert_v1/predictions.npz";REP=H/"runs/p253_repeat_physical_transformer_oof_v1/oof_predictions.npz";REPT=H/"runs/p254_repeat_physical_transformer_test_v1/test_predictions.npz";RIDGE=H/"runs/p231_depth_thermal_ir_oof_v1/oof_predictions.npz";RIDGET=H/"runs/p233_depth_thermal_ir_test_heads_v1/test_predictions.npz";PHY=H/"runs/p238_physical_token_transformer_oof_v1/oof_predictions.npz";PHYT=H/"runs/p239_physical_token_transformer_test_v1/test_predictions.npz"
def al(v,s,t):d={x:i for i,x in enumerate(s.astype(str))};return np.asarray(v)[np.asarray([d[x] for x in t.astype(str)])]
def main():
 tr,names=build_train_bank();p=np.load(P128);l=np.load(L);phy=np.load(PHY);ridge=np.load(RIDGE);rep=np.load(REP);cent=np.load(CENT)
 for n in SPLITS:
  q=tr[n];q["bank"]=np.concatenate((q["bank"],al(p["probabilities"],p["sample_ids"],q["ids"])[:,None,:],al(l["probability"],l["sample_ids"],q["ids"])[:,None,:],al(phy["probability"],phy["sample_ids"],q["ids"])[:,None,:],al(ridge["ir_thermal_probability"],ridge["sample_ids"],q["ids"])[:,None,:],al(rep["probability"],rep["sample_ids"],q["ids"])[:,None,:],al(cent["probability"],cent["sample_ids"],q["ids"])[:,None,:]),axis=1)
 names=[*names,"p128_hierarchical_multimodal","p158_lavila_frame_token","p238_physical_token","p231_ir_thermal","p253_repeat_physical","p277_physical_centroid"]
 rep,pred,prob,thr=crossfit(tr);alltr=concatenate([tr[n] for n in SPLITS]);lk=lookup_for([tr[n] for n in SPLITS]);x=features(alltr,lk,TRAIN_METADATA)
 test=build_test_bank(names[:21],names[:24]);pt=np.load(P128T);lt=np.load(LT);phyt=np.load(PHYT);ridget=np.load(RIDGET);rept=np.load(REPT);pp=al(phyt["probability"],phyt["sample_ids"],test["ids"]);av=al(phyt["available"],phyt["sample_ids"],test["ids"]);pp[~av]=test["bank"][~av,0,:];rp=al(ridget["ir_thermal_probability"],ridget["sample_ids"],test["ids"]);rav=al(ridget["ir_thermal_available"],ridget["sample_ids"],test["ids"]);rp[~rav]=test["bank"][~rav,0,:];ep=al(rept["probability"],rept["sample_ids"],test["ids"]);eav=al(rept["available"],rept["sample_ids"],test["ids"]);ep[~eav]=test["bank"][~eav,0,:];cp=al(cent["test_probability"],cent["test_sample_ids"],test["ids"]);cav=al(cent["test_available"],cent["test_sample_ids"],test["ids"]);cp[~cav]=test["bank"][~cav,0,:];test["bank"]=np.concatenate((test["bank"],al(pt["probabilities"],pt["sample_ids"],test["ids"])[:,None,:],al(lt["probability"],lt["sample_ids"],test["ids"])[:,None,:],pp[:,None,:],rp[:,None,:],ep[:,None,:],cp[:,None,:]),axis=1);lk={v:q for v,q in zip(test["ids"],test["bank"])};tx=group_features(test["ids"],test["base"],lk,posterior_feature_mode="sqrt",group_config=CONFIG,group_feature_layout="full",teacher_subset="full",grouping_lookup=lk,metadata_path=TEST_METADATA);tp=fit_probability(x,alltr["labels"],tx,.03,2.,False,0.);pr=tp.argmax(1);i=np.arange(len(pr));score=tp[i,pr]-tp[i,test["base"]];t=float(np.median(thr));route=(pr!=test["base"])&(score>=t)&test["visual_available"];out=test["base"].copy();out[route]=pr[route];O.mkdir(parents=True,exist_ok=True);sub=O/"submission_p278_centroid_group.csv";io.write_submission(sub,io.read_rows(P89),out);np.savez_compressed(O/"predictions.npz",sample_ids=test["ids"],base_prediction=test["base"],probability=tp.astype(np.float32),prediction=out,route=route,**{f"{n}_held_prediction":pred[n] for n in SPLITS},**{f"{n}_held_probability":prob[n] for n in SPLITS});total=sum(len(tr[n]["labels"]) for n in SPLITS);cor=sum(int(np.sum(pred[n]==tr[n]["labels"])) for n in SPLITS);bc=sum(int(np.sum(tr[n]["base"]==tr[n]["labels"])) for n in SPLITS);report={"stage":"P278_centroid_augmented_group_teacher","status":"complete","protocol":{"expert_names":names,"test_labels_read":False,"user_id_used_as_feature":False},"cohorts":rep,"aggregate":{"rows":total,"base_correct":bc,"correct":cor,"accuracy":cor/total,"net_vs_p89":cor-bc,"p177_reference_correct":2154},"test":{"threshold":t,"changes_vs_p89":int(route.sum()),"submission":str(sub.resolve()),"test_labels_read":False}};(O/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=="__main__":main()




