"""P306 plus seven aligned Depth+IR rows with explicit zero Thermal tokens."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np,torch
from p90_teacher_common import load_protocol
from p142_vjepa_token_transformer_oof import build_repeat_pairs,train_fold
from p253_repeat_physical_transformer_oof import PATHS,SEEDS,cfg
H=Path(__file__).resolve().parent;O=H/"runs/p321_union_full_partial_repeat_oof_v1";FULL=H/"runs/p302_union_full_physical_features_v1/features.npz";PART=H/"runs/p320_union_dir_partial_features_v1/features.npz";CONTROL=H/"runs/p306_union_full_repeat_physical_oof_v1/oof_predictions.npz"
def tokens(z):return np.concatenate([z["ir_videomaev2"],z["ir_internvideo2"],z["depth_videomaev2"],z["thermal_videomaev2"]],1).astype(np.float16)
def main():
 print("P321 tests the isolated value of seven aligned Depth+IR rows added to the frozen P306 recipe.",flush=True);p=load_protocol();sources=[np.load(q) for q in PATHS];main=np.concatenate([q["features"].astype(np.float16).reshape(len(p.labels),-1,768) for q in sources],1);a=np.load(FULL);b=np.load(PART);x=np.concatenate((main,tokens(a),tokens(b)));labels=np.concatenate((p.labels,a["labels"].astype(int),b["labels"].astype(int)));users=np.concatenate((p.users,a["users"].astype(str),b["users"].astype(str)));domain=np.zeros(len(labels),int);pairs=build_repeat_pairs(p);extra=np.arange(len(p.labels),len(labels));logits=np.zeros((len(p.labels),40),float);folds=[];device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
 for f in range(3):
  held=p.val_indices(f);hu=set(p.users[held].tolist());add=extra[~np.isin(users[extra],list(hu))];tr=np.concatenate((p.train_indices(f),add));members=[train_fold(x,labels,tr,held,domain,s+f*1000,cfg(),device,pairs,None) for s in SEEDS];logits[held]=np.mean(members,0);folds.append({"fold":f,"full_and_partial_extra_train_rows":len(add),"correct":int(np.sum(logits[held].argmax(1)==p.labels[held])),"rows":len(held)})
 prob=np.exp(logits-logits.max(1,keepdims=True));prob/=prob.sum(1,keepdims=True);old=np.load(CONTROL)["probability"].argmax(1);new=prob.argmax(1);changed=old!=new;report={"stage":"P321_union_full_partial_repeat_OOF","status":"complete","protocol":{"main_rows":len(p.labels),"full_extra_rows":len(a["labels"]),"partial_depth_ir_rows":len(b["labels"]),"missing_thermal_representation":"three zero tokens","paired_control":"P306 same architecture/seeds/config/repeat pairs","held_subject_extra_rows_excluded":True,"test_rows_loaded":0,"test_labels_read":False,"user_id_used_as_feature":False},"control":{"correct":int(np.sum(old==p.labels))},"augmented":{"correct":int(np.sum(new==p.labels)),"accuracy":float(np.mean(new==p.labels)),"net_vs_p306":int(np.sum(new==p.labels)-np.sum(old==p.labels)),"changed":int(changed.sum()),"rescued":int(np.sum(changed&(old!=p.labels)&(new==p.labels))),"harmed":int(np.sum(changed&(old==p.labels)&(new!=p.labels))),"folds":folds}};O.mkdir(parents=True,exist_ok=True);np.savez_compressed(O/"oof_predictions.npz",sample_ids=p.sample_ids,labels=p.labels,probability=prob.astype(np.float32),logits=logits.astype(np.float32));(O/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");(O/"notes.txt").write_text("Run 1: P306 plus seven aligned Depth+IR rows with zero Thermal tokens. All other training choices frozen.\n"+json.dumps(report,ensure_ascii=False)+"\n",encoding="utf-8");print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
